package team.standalone.core.ui.util

object BindingAdapterUtil {
    const val APP_TINT = "app:tint"
    const val IMAGE_URL = "image_url"
    const val IMAGE_FILE = "image_file"
    const val IMAGE_DRAWABLE = "image_drawable"
    const val IMAGE_BASE64 = "image_base64"
    const val IMAGE_PlACEHOLDER = "image_placeholder"
    const val IMAGE_ERROR = "image_error"
    const val IMAGE_ENABLED = "image_enabled"
    const val RESOURCE_ID = "resource_id"
    const val RESOURCE_PLACEHOLDER = "resource_placeholder"
    const val RESOURCE_ERROR = "resource_error"
    const val RESOURCE_ENABLED = "resource_enabled"
    const val SELECTED_TEXT = "selectedText"
    const val IS_UNDERLINED = "isUnderlined"
    const val TEXT_BIRTHDATE = "textBirthDate"
    const val FIRST_NAME = "firstName"
    const val LAST_NAME = "lastName"
    const val JAP_FORMAT_FIRST_NAME = "japFormatFirstName"
    const val JAP_FORMAT_LAST_NAME = "japFormatLastName"
    const val JAP_FORMAT_SALUTATION = "japFormatSalutation"
    const val INSTANT_DATE_SHORT = "instantDateShort"
    const val FORM_HAS_ERROR = "formHasError"
    const val FORM_ERROR = "formError"
    const val NUMBER = "number"
    const val NUMBER_GROUPED = "number_grouped"
    const val BIRTHDATE_YEAR = "birthdateYear"
    const val BIRTHDATE_MONTH = "birthdateMonth"
    const val BIRTHDATE_DAY = "birthdateDay"
    const val ERROR_TEXT = "errorText"
    const val VISIBLE_GONE = "visibleGone"
    const val VISIBLE_HIDDEN = "visibleHidden"
    const val VISIBLE_IF_NOT_EMPTY = "visibleIfNotEmpty"
    const val VISIBLE_IF_NO_SELECTED = "visibleIfNoSelected"
    const val VISIBLE_IF_NOT_NULL = "visibleIfNotNull"
    const val UNDERLINE_TEXT = "underlineText"
}